name: 'Python Hello World Action'
description: 'A simple action to print "Hello, World!" using Python'
inputs:
  message:
    description: 'The message to print'
    required: true
    default: 'Hello, Github Actions!'
    
runs:
  using: composite
  steps:
    - run: echo ${{inputs.message}}
      shell: bash

    - id: output-step
      run: echo "Hello World" >> $GITHUB_OUTPUT
      shell: bash
    
    - run: echo "Output: ${{ steps.output-step.outputs.result }}"
      shell: bash
