name: 'Python Hello World Action'
description: 'A simple action to print "Hello, World!" using Python'
inputs:
  message:
    description: 'The message to print'
    required: true
    default: 'Hello, Github Actions!'
outputs:
  result:
    value: ${{ steps.output-step.outputs.result }}
    description: 'The result of the action'
    
runs:
  using: composite
  steps:
    - run: echo ${{inputs.message}}
      shell: bash

    - id: output-step
      run: echo "result=deu boa!" >> GITHUB_OUTPUT
      shell: bash
  
